/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const img: string;
declare const double: string;
declare const view: string;
declare const linkStyle: string;

declare const __default_export__: {
	img: typeof img;
	double: typeof double;
	view: typeof view;
	linkStyle: typeof linkStyle;
};
export default __default_export__;
