/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const mainContainer: string;

declare const __default_export__: {
	mainContainer: typeof mainContainer;
};
export default __default_export__;
