/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const margin: string;
declare const headerWrapper: string;
declare const header: string;
declare const navigationRow: string;
declare const navigationColumn: string;
declare const img: string;
declare const double: string;
declare const view: string;
declare const flexRow: string;
declare const hideButton: string;
declare const linkStyle: string;

declare const __default_export__: {
	margin: typeof margin;
	headerWrapper: typeof headerWrapper;
	header: typeof header;
	"navigation-row": typeof navigationRow;
	"navigation-column": typeof navigationColumn;
	img: typeof img;
	double: typeof double;
	view: typeof view;
	flexRow: typeof flexRow;
	hideButton: typeof hideButton;
	linkStyle: typeof linkStyle;
};
export default __default_export__;
