/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const card: string;
declare const linkRoute: string;
declare const row: string;
declare const form: string;
declare const marginInput: string;
declare const backButton: string;
declare const trix: string;
declare const trixToolbar: string;
declare const trixError: string;
declare const technologies: string;
declare const technologyMargin: string;
declare const technologyMarginError: string;
declare const red: string;
declare const agreemErr: string;
declare const addressContainer: string;
declare const stepperContainer: string;
declare const dropzoneError: string;
declare const dropzoneContainer: string;
declare const dropzoneFlex: string;
declare const dropzoneUploaded: string;
declare const addOfferContainer: string;
declare const topContainer: string;
declare const topContainerCompany: string;
declare const middleContainer: string;
declare const widthPadding: string;
declare const bottomSection: string;
declare const flexWidth: string;
declare const mapContainer: string;
declare const width100: string;
declare const techStackContainer: string;
declare const technologyTitle: string;
declare const agreements: string;
declare const titleMargin: string;
declare const headerInformation: string;
declare const checkboxContainer: string;

declare const __default_export__: {
	card: typeof card;
	linkRoute: typeof linkRoute;
	row: typeof row;
	form: typeof form;
	marginInput: typeof marginInput;
	backButton: typeof backButton;
	trix: typeof trix;
	"trix-toolbar": typeof trixToolbar;
	trixError: typeof trixError;
	technologies: typeof technologies;
	technologyMargin: typeof technologyMargin;
	technologyMarginError: typeof technologyMarginError;
	red: typeof red;
	agreemErr: typeof agreemErr;
	addressContainer: typeof addressContainer;
	stepperContainer: typeof stepperContainer;
	dropzoneError: typeof dropzoneError;
	dropzoneContainer: typeof dropzoneContainer;
	dropzoneFlex: typeof dropzoneFlex;
	dropzoneUploaded: typeof dropzoneUploaded;
	addOfferContainer: typeof addOfferContainer;
	topContainer: typeof topContainer;
	topContainerCompany: typeof topContainerCompany;
	middleContainer: typeof middleContainer;
	widthPadding: typeof widthPadding;
	bottomSection: typeof bottomSection;
	flexWidth: typeof flexWidth;
	mapContainer: typeof mapContainer;
	width100: typeof width100;
	techStackContainer: typeof techStackContainer;
	technologyTitle: typeof technologyTitle;
	agreements: typeof agreements;
	titleMargin: typeof titleMargin;
	headerInformation: typeof headerInformation;
	checkboxContainer: typeof checkboxContainer;
};
export default __default_export__;
