/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const paddingLeft: string;
declare const paddingRight: string;
declare const paddingRight30: string;
declare const linkStyle: string;
declare const spanLine: string;
declare const bg: string;
declare const intro: string;
declare const cards: string;
declare const header: string;
declare const price: string;
declare const description: string;
declare const point: string;
declare const text: string;
declare const program: string;
declare const h1offer: string;
declare const priceTable: string;
declare const card: string;
declare const _package: string;
declare const packageMiddle: string;
declare const title: string;
declare const pricetxt: string;
declare const pricecurr: string;
declare const benefits: string;
declare const iconActive: string;
declare const iconNotActive: string;
declare const btn: string;
declare const recom: string;
declare const choosePlanContainer: string;

declare const __default_export__: {
	paddingLeft: typeof paddingLeft;
	paddingRight: typeof paddingRight;
	paddingRight30: typeof paddingRight30;
	linkStyle: typeof linkStyle;
	spanLine: typeof spanLine;
	bg: typeof bg;
	intro: typeof intro;
	cards: typeof cards;
	header: typeof header;
	price: typeof price;
	description: typeof description;
	point: typeof point;
	text: typeof text;
	program: typeof program;
	h1offer: typeof h1offer;
	priceTable: typeof priceTable;
	card: typeof card;
	"package": typeof _package;
	packageMiddle: typeof packageMiddle;
	title: typeof title;
	pricetxt: typeof pricetxt;
	pricecurr: typeof pricecurr;
	benefits: typeof benefits;
	iconActive: typeof iconActive;
	iconNotActive: typeof iconNotActive;
	btn: typeof btn;
	recom: typeof recom;
	choosePlanContainer: typeof choosePlanContainer;
};
export default __default_export__;
