/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dot: string;
declare const dotClicked: string;
declare const language: string;
declare const desc: string;
declare const close: string;
declare const skillContainer: string;
declare const techStackList: string;
declare const flex: string;

declare const __default_export__: {
	dot: typeof dot;
	dotClicked: typeof dotClicked;
	language: typeof language;
	desc: typeof desc;
	close: typeof close;
	skillContainer: typeof skillContainer;
	techStackList: typeof techStackList;
	flex: typeof flex;
};
export default __default_export__;
