/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const tagsPadding: string;
declare const color: string;
declare const img: string;
declare const flex: string;
declare const flexend: string;
declare const tag: string;
declare const offer: string;
declare const top: string;
declare const banner: string;
declare const card: string;
declare const name: string;
declare const logoCircle: string;
declare const circle: string;
declare const logo: string;
declare const titleSalary: string;
declare const title: string;
declare const apply: string;
declare const MuiSvgIconRoot: string;
declare const itSkills: string;
declare const skill: string;
declare const flexRow: string;
declare const skillCircle: string;
declare const companyDetails: string;
declare const linkStyle: string;
declare const techStack: string;
declare const agreementsContainer: string;
declare const titleTech: string;
declare const insideTech: string;
declare const techSkills: string;
declare const techSkill: string;
declare const description: string;
declare const additionalDesc: string;
declare const form: string;
declare const inputs: string;
declare const agreements: string;
declare const backButton: string;
declare const fontSalary: string;
declare const fontTitle: string;
declare const dot: string;
declare const dotClicked: string;
declare const language: string;
declare const desc: string;
declare const salaryStreetDetail: string;
declare const logoImg: string;
declare const mapContainer: string;

declare const __default_export__: {
	main: typeof main;
	tagsPadding: typeof tagsPadding;
	color: typeof color;
	img: typeof img;
	flex: typeof flex;
	flexend: typeof flexend;
	tag: typeof tag;
	offer: typeof offer;
	top: typeof top;
	banner: typeof banner;
	card: typeof card;
	name: typeof name;
	logoCircle: typeof logoCircle;
	circle: typeof circle;
	logo: typeof logo;
	titleSalary: typeof titleSalary;
	title: typeof title;
	apply: typeof apply;
	"MuiSvgIcon-root": typeof MuiSvgIconRoot;
	itSkills: typeof itSkills;
	skill: typeof skill;
	flexRow: typeof flexRow;
	skillCircle: typeof skillCircle;
	companyDetails: typeof companyDetails;
	linkStyle: typeof linkStyle;
	techStack: typeof techStack;
	agreementsContainer: typeof agreementsContainer;
	titleTech: typeof titleTech;
	insideTech: typeof insideTech;
	techSkills: typeof techSkills;
	techSkill: typeof techSkill;
	description: typeof description;
	additionalDesc: typeof additionalDesc;
	form: typeof form;
	inputs: typeof inputs;
	agreements: typeof agreements;
	backButton: typeof backButton;
	fontSalary: typeof fontSalary;
	fontTitle: typeof fontTitle;
	dot: typeof dot;
	dotClicked: typeof dotClicked;
	language: typeof language;
	desc: typeof desc;
	salaryStreetDetail: typeof salaryStreetDetail;
	logoImg: typeof logoImg;
	mapContainer: typeof mapContainer;
};
export default __default_export__;
