/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tab: string;
declare const activeTab: string;
declare const linkStyle: string;

declare const __default_export__: {
	tab: typeof tab;
	activeTab: typeof activeTab;
	linkStyle: typeof linkStyle;
};
export default __default_export__;
