/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const linkRouteAllBtn: string;
declare const linkRoute: string;
declare const salaryHeader: string;
declare const sliderWidth: string;
declare const salaryContainer: string;
declare const width100: string;
declare const marginRight15: string;
declare const view: string;
declare const whiteBg: string;
declare const border: string;
declare const flex: string;
declare const activeButton: string;
declare const offers: string;
declare const leafletContainer: string;
declare const langBtn: string;
declare const langBtnActive: string;
declare const test: string;
declare const logoLang: string;
declare const buttonContainer: string;
declare const textTitleMobile: string;
declare const buttonListMobile: string;
declare const expContainerMobile: string;
declare const salaryContainerMobile: string;
declare const darkPosition: string;
declare const languagePosition: string;
declare const languagePositionMobile: string;
declare const salaryExpContainer: string;
declare const filters: string;
declare const langButtonContainer: string;
declare const langImg: string;
declare const langButtonMobile: string;
declare const iconContainerAdd: string;

declare const __default_export__: {
	linkRouteAllBtn: typeof linkRouteAllBtn;
	linkRoute: typeof linkRoute;
	salaryHeader: typeof salaryHeader;
	sliderWidth: typeof sliderWidth;
	salaryContainer: typeof salaryContainer;
	width100: typeof width100;
	marginRight15: typeof marginRight15;
	view: typeof view;
	whiteBg: typeof whiteBg;
	border: typeof border;
	flex: typeof flex;
	activeButton: typeof activeButton;
	offers: typeof offers;
	"leaflet-container": typeof leafletContainer;
	langBtn: typeof langBtn;
	langBtnActive: typeof langBtnActive;
	test: typeof test;
	logoLang: typeof logoLang;
	buttonContainer: typeof buttonContainer;
	textTitleMobile: typeof textTitleMobile;
	buttonListMobile: typeof buttonListMobile;
	expContainerMobile: typeof expContainerMobile;
	salaryContainerMobile: typeof salaryContainerMobile;
	darkPosition: typeof darkPosition;
	languagePosition: typeof languagePosition;
	languagePositionMobile: typeof languagePositionMobile;
	salaryExpContainer: typeof salaryExpContainer;
	filters: typeof filters;
	langButtonContainer: typeof langButtonContainer;
	langImg: typeof langImg;
	langButtonMobile: typeof langButtonMobile;
	iconContainerAdd: typeof iconContainerAdd;
};
export default __default_export__;
