/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const spanStyle: string;
declare const linkStyle: string;
declare const flexRow: string;
declare const flexColumn: string;
declare const popupContainer: string;
declare const iconSize: string;
declare const bounce: string;
declare const jump: string;

declare const __default_export__: {
	spanStyle: typeof spanStyle;
	linkStyle: typeof linkStyle;
	flexRow: typeof flexRow;
	flexColumn: typeof flexColumn;
	popupContainer: typeof popupContainer;
	iconSize: typeof iconSize;
	bounce: typeof bounce;
	jump: typeof jump;
};
export default __default_export__;
