/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const root: string;

declare const __default_export__: {
	root: typeof root;
};
export default __default_export__;
