/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const noOffersDash: string;
declare const dashboardText: string;
declare const column: string;
declare const socialButton: string;
declare const row: string;
declare const rowIcon: string;
declare const pad: string;
declare const img: string;
declare const one: string;
declare const double: string;
declare const register: string;
declare const socials: string;
declare const padding: string;
declare const btn: string;
declare const center: string;
declare const bottomSign: string;
declare const imgContainer: string;
declare const socialImg: string;
declare const spanWeight: string;

declare const __default_export__: {
	noOffersDash: typeof noOffersDash;
	dashboardText: typeof dashboardText;
	column: typeof column;
	socialButton: typeof socialButton;
	row: typeof row;
	rowIcon: typeof rowIcon;
	pad: typeof pad;
	img: typeof img;
	one: typeof one;
	double: typeof double;
	register: typeof register;
	socials: typeof socials;
	padding: typeof padding;
	btn: typeof btn;
	center: typeof center;
	bottomSign: typeof bottomSign;
	imgContainer: typeof imgContainer;
	socialImg: typeof socialImg;
	spanWeight: typeof spanWeight;
};
export default __default_export__;
